version: '3.8'

services:
  bot:
    build: .
    container_name: support_bot
    depends_on:
      - db
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
      # - ./static:/app/static
    command: python -m src.main

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: